site_name: Reisender

theme:
  name: material
  palette:
    scheme: slate
    primary: green
  features:
    - navigation.tabs

plugins:
  - search
  - tags
  - autorefs

nav:
  - Home: index.md
  - About: about.md
